"""
CLI script to run the evaluation pipeline.
Usage: python scripts/evaluate.py --test_file scripts/test_cases.json
"""

import sys
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import typer
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from loguru import logger

from src.pipeline import RAGPipeline

app = typer.Typer()
console = Console()

# Default test cases — replace with your own
DEFAULT_TEST_CASES = [
    {
        "question": "What is the main topic of the documents?",
        "answer": None,  # Will be auto-generated by the pipeline
        "context": None,
    }
]


@app.command()
def evaluate(
    test_file: str = typer.Option(None, "--test_file", help="JSON file with test cases"),
    auto_generate: bool = typer.Option(True, "--auto_generate", help="Auto-generate answers from pipeline"),
    output: str = typer.Option("eval_results.json", "--output", help="Output JSON file"),
):
    """Run evaluation suite on the RAG pipeline."""

    console.print("\n[bold blue]RAG Evaluation Pipeline[/bold blue]\n")

    pipeline = RAGPipeline()

    # Load test cases
    if test_file and Path(test_file).exists():
        with open(test_file) as f:
            test_cases = json.load(f)
        console.print(f"Loaded {len(test_cases)} test cases from {test_file}")
    else:
        console.print("[yellow]No test file provided — using default test cases[/yellow]")
        test_cases = DEFAULT_TEST_CASES

    # Auto-generate answers if not provided
    if auto_generate:
        console.print("[cyan]Generating answers from pipeline...[/cyan]")
        enriched = []
        for case in test_cases:
            response = pipeline.query(case["question"])
            enriched.append({
                "question": case["question"],
                "answer": response.answer,
                "context": response.context,
            })
        test_cases = enriched

    # Run evaluation
    console.print(f"[cyan]Evaluating {len(test_cases)} cases...[/cyan]\n")
    summary = pipeline.evaluator.evaluate_batch(test_cases)

    # Display results table
    table = Table(title="Evaluation Results")
    table.add_column("Metric", style="cyan")
    table.add_column("Score", style="green")
    table.add_column("Interpretation")

    def interpret(score: float) -> str:
        if score >= 0.8:
            return "[green]Excellent[/green]"
        elif score >= 0.6:
            return "[yellow]Good[/yellow]"
        elif score >= 0.4:
            return "[orange1]Fair[/orange1]"
        else:
            return "[red]Poor[/red]"

    s = summary.to_dict()["summary"]
    table.add_row("Faithfulness", f"{s['avg_faithfulness']:.3f}", interpret(s["avg_faithfulness"]))
    table.add_row("Answer Relevance", f"{s['avg_relevance']:.3f}", interpret(s["avg_relevance"]))
    table.add_row("Retrieval Precision", f"{s['avg_retrieval_precision']:.3f}", interpret(s["avg_retrieval_precision"]))
    table.add_row("─" * 20, "─" * 10, "─" * 15)
    table.add_row("[bold]Overall Score[/bold]", f"[bold]{s['avg_overall_score']:.3f}[/bold]", interpret(s["avg_overall_score"]))

    console.print(table)

    # Save results
    output_path = Path(output)
    with open(output_path, "w") as f:
        json.dump(summary.to_dict(), f, indent=2)
    console.print(f"\n[green]Results saved to {output_path}[/green]")


if __name__ == "__main__":
    app()
